name: Check pull request title

on:
  pull_request:
    branches:
      - "*"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@v3.0.0
        with:
          regexp: "/^\[((WU)-[0-9]+No Ticket)\].*$/"
