name: Check pull request title

on:
  pull_request:
    branches: [ master ]
    types: [ edited, opened, reopened, synchronize, labeled, unlabeled ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@v3.0.0
        with:
          regexp: "^\\[((WU)-[1-9][0-9]*|No Ticket)\\] - .*$"
